spring:
  application.name: Agentic-AI

  datasource:
    url: jdbc:postgresql://localhost:5432/agentic_ai
    username: admin
    password: "1234"

  autoconfigure:
    exclude:
      - org.springframework.ai.autoconfigure.chat.ChatAutoConfiguration
      - org.springframework.ai.autoconfigure.vectorstore.VectorStoreAutoConfiguration
      - org.springframework.ai.autoconfigure.embedding.EmbeddingAutoConfiguration
      - org.springframework.ai.autoconfigure.observation.ObservationAutoConfiguration
      - org.springframework.ai.model.google.genai.autoconfigure.chat.GoogleGenAiChatAutoConfiguration

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



    ai:
      vectorstore:
        pgvector:
          table-name: vector_store
          dimensions: 768

ai:
  gemini:
    api-key: ${GOOGLE_GEMINI_KEY}
    reasoning: gemini-3-flash-preview
